### PR TITLE
doc: typo in readme

### PR DESCRIPTION
**Pull request by romgrk**

### CODE REVIEW

**Comment by kevinaboos** [comment]
Thanks @romgrk, I have coincidentally fixed this a few days ago in another ongoing branch that will be merged soon, so I'm closing this in favor of that. Appreciate the proofreading!

**Comment by kevinaboos** [comment]
Addressed in #329 as promised. Thanks again.

**Comment by romgrk** [comment]
:+1:

**Comment by romgrk** [comment]
There were quite a few typos/missing words in the high-level overview, are you planning to update it soon? Pretty interesting project btw :)

**Comment by kevinaboos** [comment]
The `book`-style docs? Yeah, I haven't touched those in a while, and some of them weren't written by me. I probably need to go through and do a full re-write of everything there since it's out of date.
If you notice specific problems there, feel free to file another PR, but no worries if you don't want to waste your time on that. :) 

Thanks!

**Pull request closed without merging**
