### PR TITLE
Uncomment remaining passing lints

### PR DESCRIPTION
**Pull request by dcampbell24**
I added the rest of the passing lints and renamed one lint. eval-order-dependence -> mixed_read_write_in_expression

### CODE REVIEW

**Comment by dcampbell24** [comment]
I ran it with --all-features and --workspace.

**Comment by tsoutsman** [comment]
Thanks, it mostly looks good, but for the sake of consistency, could you please rename `mixed_read_write_in_expression` to `mixed-read-write-in-expression`?

Also, for posterity's sake, the rename from `eval-order-dependence` is required because [the lint name was changed](https://rust-lang.github.io/rust-clippy/master/#mixed_read_write_in_expression).

**Review by tsoutsman — APPROVED** [review]

**Comment by tsoutsman** [comment]
Thanks.

**Comment by kevinaboos** [comment]
Thanks @dcampbell24!

**Pull request merged**
